#!/bin/bash
yum update -y
yum install -y httpd
wget https://dynamic-web-files.s3.amazonaws.com/startbootstrap-freelancer-gh-pages.zip
unzip startbootstrap-freelancer-gh-pages.zip
cp -r startbootstrap-freelancer-gh-pages/* /var/www/html
rm -rf startbootstrap-freelancer-gh-pages main.zip
systemctl enable httpd
systemctl start httpd